id: 698229bb7a66e90019cf7a5e
networkId: "N8zYF6HoMSfFzLP6n1iWTnuqMYvyNk9GZH9pHAPpCVmWpyEo"
nodes:
  - peerId: 12D3KooWRtvesqvjK52LQECRWpj9is6jxFrotCBdsBy58QLdVcx6
    addresses:
      - localhost:2001
    types:
      - tree
  - peerId: 12D3KooWCBpM3urQRQcuzdjS6yuqHBAeYFYcpbg6kXWVHShnu37b
    addresses:
      - localhost:2002
    types:
      - tree
  - peerId: 12D3KooWAn5WHDuSYxEypkrTRkZLjPCoRg7AjCUxq25mMA4MsS1L
    addresses:
      - localhost:2003
    types:
      - tree
  - peerId: 12D3KooWFAQRseuZbyPNFK1gwK5UBWNGwo68h4KPv7YQN6UWgzBB
    addresses:
      - localhost:2004
    types:
      - coordinator
  - peerId: 12D3KooWKgfr5xqdKNucQGbYjRHcU4kQWJYrQh1qrE7BZNQvjona
    addresses:
      - localhost:2005
    types:
      - file
  - peerId: 12D3KooWG6BPJirMGEqGJxLNpFd1oiGtMHZepBxsuzzexH3DULyz
    addresses:
      - localhost:2006
    types:
      - consensus
