id: 698216b12dcc850019d03c7f
networkId: "N7qz1pzYKTreJdwrgCk3EN2fLwZKoQuZQRjfowVPGDzMENRG"
nodes:
  - peerId: 12D3KooWCnk3xXoso2GBDXjpj5NLa1qBuFeT5e8waqbSbr4rZ2pi
    addresses:
      - localhost:1001
    types:
      - tree
  - peerId: 12D3KooWQo6tymeqhxAyk9yk2S1YSRLG1xn2v4A8Nz7CpqPFvySE
    addresses:
      - localhost:1002
    types:
      - tree
  - peerId: 12D3KooWGFqHCcFp94A937SuycuDtaRZPHb7KvzEs1NRXjJjC9tz
    addresses:
      - localhost:1003
    types:
      - tree
  - peerId: 12D3KooWKmX426328LRe1VYgzpMXt7uD5fAcc2yZvZrt5tBZK1rL
    addresses:
      - localhost:1004
    types:
      - coordinator
  - peerId: 12D3KooWEaxcpuu9cMpASCJWpTxf55Pc1PT8on84WfdM7iGnC7iY
    addresses:
      - localhost:1005
    types:
      - file
  - peerId: 12D3KooWRFn3jvdUCBbHGwGrjovNT2Ssbr8jgVFYr1jo5h6b3TYL
    addresses:
      - localhost:1006
    types:
      - consensus
